# Generated by Django 5.1.1 on 2024-09-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointsAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payer',
            name='id',
        ),
        migrations.AlterField(
            model_name='payer',
            name='payer',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
